# Generated by Django 5.2.3 on 2025-07-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colesterol',
            name='hdl',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colesterol',
            name='ldl',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glicemia',
            name='glic',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressaoarterial',
            name='alta',
            field=models.IntegerField(default=2342342),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressaoarterial',
            name='baixa',
            field=models.IntegerField(default=4345),
            preserve_default=False,
        ),
    ]
